// <auto-generated />
using System;
using Kilo.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kilo.Persistence.Migrations
{
    [DbContext(typeof(KiloDbContext))]
    [Migration("20261008032930_OrganizeUserEntity")]
    partial class OrganizeUserEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kilo.Persistence.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasMaxLength(27)
                        .HasColumnType("text")
                        .HasColumnName("clerk_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MeasurementSystem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("text")
                        .HasDefaultValue("imperial")
                        .HasColumnName("measurement_system");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("UTC")
                        .HasColumnName("time_zone");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasAlternateKey("ClerkUserId")
                        .HasName("users_clerk_user_id_key");

                    b.ToTable("users", "public", t =>
                        {
                            t.HasCheckConstraint("users_clerk_user_id_check", "btrim(clerk_user_id) <> ''");

                            t.HasCheckConstraint("users_measurement_system_check", "measurement_system IN ('imperial', 'metric')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
