// <auto-generated />
using System;
using Kilo.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kilo.Persistence.Migrations
{
    [DbContext(typeof(KiloDbContext))]
    [Migration("20261008234727_AddRoutines")]
    partial class AddRoutines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kilo.Persistence.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("BrandName")
                        .HasColumnType("text")
                        .HasColumnName("brand_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("exercises_pkey");

                    b.HasIndex("UserId", "Name")
                        .HasDatabaseName("exercises_active_list")
                        .HasFilter("archived_at IS NULL");

                    b.ToTable("exercises", "public", t =>
                        {
                            t.HasCheckConstraint("exercises_brand_name_check", "brand_name IS NULL OR (btrim(brand_name) <> '' AND length(brand_name) <= 100)");

                            t.HasCheckConstraint("exercises_name_check", "btrim(name) <> ''");

                            t.HasCheckConstraint("exercises_user_id_check", "user_id IS NULL OR user_id > 0");
                        });
                });

            modelBuilder.Entity("Kilo.Persistence.Entities.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("routines_pkey");

                    b.HasAlternateKey("Id", "UserId")
                        .HasName("routines_id_user_id_key");

                    b.HasIndex("UserId", "Name")
                        .HasDatabaseName("routines_active_list")
                        .HasFilter("archived_at IS NULL");

                    b.ToTable("routines", "public", t =>
                        {
                            t.HasCheckConstraint("routines_name_check", "btrim(name) <> ''");
                        });
                });

            modelBuilder.Entity("Kilo.Persistence.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("ClerkUserId")
                        .IsRequired()
                        .HasMaxLength(27)
                        .HasColumnType("text")
                        .HasColumnName("clerk_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MeasurementSystem")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("text")
                        .HasDefaultValue("imperial")
                        .HasColumnName("measurement_system");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("UTC")
                        .HasColumnName("time_zone");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasAlternateKey("ClerkUserId")
                        .HasName("users_clerk_user_id_key");

                    b.ToTable("users", "public", t =>
                        {
                            t.HasCheckConstraint("users_clerk_user_id_check", "btrim(clerk_user_id) <> ''");

                            t.HasCheckConstraint("users_measurement_system_check", "measurement_system IN ('imperial', 'metric')");
                        });
                });

            modelBuilder.Entity("Kilo.Persistence.Entities.Exercise", b =>
                {
                    b.HasOne("Kilo.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("exercises_user_id_fkey");
                });

            modelBuilder.Entity("Kilo.Persistence.Entities.Routine", b =>
                {
                    b.HasOne("Kilo.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("routines_user_id_fkey");
                });
#pragma warning restore 612, 618
        }
    }
}
